site_name: Acelen - Algorithm Theoretical Basis Document (ATBD)
site_author: Bernard Silva de Oliveira
copyright: ATBD versão 5.0 — agosto de 2026 · LAPIG/UFG–FUNAPE × Acelen Renováveis
theme:
  name: material # O estilo material
  custom_dir: overrides # Sobrescreve o partial da logo para exibir LAPIG + UFG + Acelen separadas

  # Recursos visuais (Habilita a barra de pesquisa que expande e abas se necessário)
  features:
    - navigation.tabs       # Adiciona o menu horizontal no topo (Home, Setup, Plugins...)
    - navigation.sections   # Organiza o menu lateral em blocos visuais
    - search.suggest        # Sugestões inteligentes na busca
    - search.highlight      # Destaca o texto que o usuário buscou
    - toc.integrate

repo_name: LAPIG-UFG/toolkit-acelen  # Nome que aparecerá ao lado do ícone
repo_url: https://github.com/lapig-ufg/lapig-acelen #O link do endereço do github do lapig na acelen

nav:
  - 'Pagina Principal': 'index.md'
  - 'Introdução': '01_INTRODUCAO.md'
  - 'Base Teórica': '02_BASE_TEORICA.md'
  - 'Descrição e Abordagem do Algoritmo': '03_DESCRICAO_ABORDAGEM_DO_ALGORITMO.md'
  - 'Considerações de Implementação': '04_CONSIDERACOES_DE_IMPLEMENTACAO.md'
  - 'Referências Bibliográficas': '05_REFERENCIAS.md'
 
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:    #Ativar as fórmulas matemáticas no github.io
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
